version: '3.8'

services:
  gladsheim-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      RUST_LOG: debug
    volumes:
      - ./target:/app/target
      - ./tests:/app/tests
      - ./src:/app/src
    command: cargo test --release
